UygulamaArayuz/KutuphaneWeb/KutuphaneWeb/Controllers/YayinEviController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using Microsoft.AspNet.Identity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KutuphaneWeb.Models;

namespace KutuphaneWeb.Controllers
{
    public class YayinEviController : Controller
    {
        private KutuphaneDBEntities db = new KutuphaneDBEntities();

        // GET: /YayinEvi/
        public ActionResult Index()
        {
            return View(db.YAYIN_EVI.ToList());
        }

        // GET: /YayinEvi/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YAYIN_EVI yayin_evi = db.YAYIN_EVI.Find(id);
            if (yayin_evi == null)
            {
                return HttpNotFound();
            }
            return View(yayin_evi);
        }

        // GET: /YayinEvi/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /YayinEvi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="yayinEviId,yayinEviAdi,adress,kayitTarihi,kullaniciId,guncellemeTarihi")] YAYIN_EVI yayin_evi)
        {
            yayin_evi.kayitTarihi = DateTime.Now;
            yayin_evi.kullaniciId = User.Identity.GetUserName();
            if (ModelState.IsValid)
            {
                db.YAYIN_EVI.Add(yayin_evi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(yayin_evi);
        }

        // GET: /YayinEvi/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YAYIN_EVI yayin_evi = db.YAYIN_EVI.Find(id);
            if (yayin_evi == null)
            {
                return HttpNotFound();
            }
            return View(yayin_evi);
        }

        // POST: /YayinEvi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="yayinEviId,yayinEviAdi,adress,kayitTarihi,kullaniciId,guncellemeTarihi")] YAYIN_EVI yayin_evi)
        {
            yayin_evi.guncellemeTarihi = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(yayin_evi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(yayin_evi);
        }

        // GET: /YayinEvi/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YAYIN_EVI yayin_evi = db.YAYIN_EVI.Find(id);
            if (yayin_evi == null)
            {
                return HttpNotFound();
            }
            return View(yayin_evi);
        }

        // POST: /YayinEvi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            YAYIN_EVI yayin_evi = db.YAYIN_EVI.Find(id);
            db.YAYIN_EVI.Remove(yayin_evi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UygulamaArayuz/KutuphaneWeb/KutuphaneWeb/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using Microsoft.AspNet.Identity;
using System.Web;
using System.Web.Mvc;
using KutuphaneWeb.Models;

namespace KutuphaneWeb.Controllers
{
    public class YazarController : Controller
    {
        private KutuphaneDBEntities db = new KutuphaneDBEntities();

        // GET: /Yazar/
        public ActionResult Index()
        {
            return View(db.YAZAR.ToList());
        }

        // GET: /Yazar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YAZAR yazar = db.YAZAR.Find(id);
            if (yazar == null)
            {
                return HttpNotFound();
            }
            return View(yazar);
        }

        // GET: /Yazar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Yazar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="yazarId,yazarAdi,yazarSoyadi,kayitTarihi,kullaniciId,guncellemeTarihi")] YAZAR yazar)
        {
            yazar.kayitTarihi = DateTime.Now;
            yazar.kullaniciId = User.Identity.GetUserName();
            if (ModelState.IsValid)
            {
                db.YAZAR.Add(yazar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(yazar);
        }

        // GET: /Yazar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YAZAR yazar = db.YAZAR.Find(id);
            if (yazar == null)
            {
                return HttpNotFound();
            }
            return View(yazar);
        }

        // POST: /Yazar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="yazarId,yazarAdi,yazarSoyadi,kayitTarihi,kullaniciId,guncellemeTarihi")] YAZAR yazar)
        {
            yazar.guncellemeTarihi = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(yazar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(yazar);
        }

        // GET: /Yazar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YAZAR yazar = db.YAZAR.Find(id);
            if (yazar == null)
            {
                return HttpNotFound();
            }
            return View(yazar);
        }

        // POST: /Yazar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            YAZAR yazar = db.YAZAR.Find(id);
            db.YAZAR.Remove(yazar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UygulamaArayuz/KutuphaneWeb/KutuphaneWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KutuphaneWeb</title>
    @Styles.Render("~/Content/bootstrap.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="logo">
                    <img src="~/Content/image/logo.png" height="70" width="80" />
                </div>

            </div>
            <div class="menu">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Ana Sayfa", "Index", "Home")
                    </li>
                    <li style="width: 200px">
                        @Html.ActionLink("Kütüphane İşlemleri", "", "")
                    <ul class="sub-menu">
                        <li>@Html.ActionLink("Kütüphane Ekle", "Create", "Kutuphane")</li>
                        <li>@Html.ActionLink("Kullanıcı Ekle", "Create", "KullaniciDetay")</li>
                    </ul>
                </li>
                    <li style="width:200px">
                        @Html.ActionLink("Kitap İşlemleri", "", "")
                        <ul class="sub-menu">
                            <li>@Html.ActionLink("Kitap Ekle", "Create", "Kitap")</li>
                            <li>@Html.ActionLink("Kitap Listele", "Index", "Kitap")</li>
                            <li>@Html.ActionLink("Yazar Ekle", "Create", "Yazar")</li>
                            <li>@Html.ActionLink("YayınEvi Ekle", "Create", "YayinEvi")</li>
                            


                        </ul>
                    </li>
                    <li style="width: 250px">
                        @Html.ActionLink("Ödünç Kitap İşlemleri", "", "")
                        <ul class="sub-menu">
                            <li>@Html.ActionLink("Ödünç Kitap Ver", "Create", "OduncKitap")</li>
                            <li>@Html.ActionLink("Üye Kaydet", "Create", "Uye")</li>
                            <li>@Html.ActionLink("Üye Listele", "Index", "Uye")</li>
                        </ul>
                    </li>
                </ul>
                <li style="width:1000px; ">
                    @Html.Partial("_LoginPartial")
                </li>
            </div>
            </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KütüphaneWEB</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>